general:
  kiosk-mode: full
  autofit: true

target:
  login-method: local
  username: username
  password: example-password
  playlist: false
  URL: http://examplesitewithdifferentfieldnames


custom:
  fieldname-username-c: _username
  fieldname-password-c: _password